version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    command: sh -c "service nginx start && python web-app-code.py"
    restart: always
    depends_on:
      - flask-app

  flask-app:
    build: .
    command: python web-app-code.py
    volumes:
      - .:/app
    expose:
      - "5000"
